---
apiVersion: v1
kind: Pod
metadata:
  name: lb-hook
  labels:
    app: lb-hook
spec:
  containers:
  - name: lb-hook
    image: lb-hook:latest
    # args: ["--endpoint", "https://lbapi-staging.paas2.uninett.no/"]
    imagePullPolicy: Never
    env:
    - name: LBC_ENDPOINT
      value: "https://lbapi-staging.paas2.uninett.no/"
    - name: LBC_PEERS
      value: "127.0.0.1,0.0.0.0"
    - name: LBC_TOKEN
      value: "mysecrettoken1234567890123456789"

---
apiVersion: v1
kind: Service
metadata:
  name: lb-hook
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: lb-hook
