
---
apiVersion: v1
kind: Pod
metadata:
  name: lb-api-test
  labels:
    app: lb-api-test
spec:
  containers:
  - name: lb-api-test
    image: lb-api-test:latest
    imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: lb-api-test
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: lb-api-test
