---
apiVersion: v1
kind: Pod
metadata:
  name: lb-hook
  labels:
    app: lb-hook
spec:
  containers:
  - name: lb-hook
    image: lb-hook:latest
    imagePullPolicy: Never
    env:
    - name: lbcontroller_ENDPOINT
      value: "http://lb-api-test"

---
apiVersion: v1
kind: Service
metadata:
  name: lb-hook
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: lb-hook
