apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    testing.com/here: true
spec:
  ports:
  - port: 80
    name: web
  type: LoadBalancer
  selector:
    app: nginx

